import {update} from 'lodash'
import {GOOGLE_MAPS_KEY} from '../constants/constants'

const EndPoints = {
    callThirdPartyApi: '/third-party-api',
    // Google Maps
    getLatLongFromAddress: `https://maps.googleapis.com/maps/api/geocode/json?key=${GOOGLE_MAPS_KEY}&language=en`,
    getPlaceAddress: `https://maps.googleapis.com/maps/api/place/autocomplete/json?key=${GOOGLE_MAPS_KEY}`,
    getLocationFromAddress: `https://maps.googleapis.com/maps/api/geocode/json?&sensor=true&key=${GOOGLE_MAPS_KEY}`,
    getAddressFromReverseGeocoding: `https://maps.googleapis.com/maps/api/geocode/json?key=${GOOGLE_MAPS_KEY}`,
    getTimeZoneFromLatLong: `https://maps.googleapis.com/maps/api/timezone/json?key=${GOOGLE_MAPS_KEY}`,

    // Digi Signer
    digiSignerSignatureRequest: '/hiring/custom_doc_for_sign',

    // Auth
    login: '/master/login',
    forgotPassword: '/forgot-password',
    getCompanyProfile: '/setting/get-company-profile',
    getCompanyProfileWithoutAuth: '/get-company-profile-without-auth',
    updateCompanyProfile: '/setting/update-company-profile',
    logout: '/master/logout',
    getUserProfile: '/get_userdata',
    changePassword: '/change_password',

    //Global
    getAllLocationList: '/setting/AllGeneralCodeList',
    getAllStatesAndCities: '/city_by_state',
    getUsedStates: '/setting/get-all-user-state',
    getcityList: '/cities_by_state_id',
    getRedlineFromLocation: '/setting/get_data_from_location',

    //Admin > Setup > Company
    getCompanySetting: '/setting/get-company-setting',
    updateCompanySetting: '/setting/setup-active-inactive',

    // Admin > Setup > Company Margin
    getCompanyMargin: '/setting/get_company_margin',
    updateCompanyMargin: '/setting/update_company_margin',

    // Admin > Setting
    getOverridesOnTwoAccountStatus: '/management/get_override_system_status?id=1',
    updateOverridesOnTwoAccountStatus: '/management/override_system_status',
    getCompanyReconciliation: '/setting/getReconciliationSchedule',
    deleteReconciliationPeriod: '/setting/deleteReconciliationSchedule',
    getCompanyGlobalReconciliation: '/setting/get-company-global-reconciliation',
    CompanyGlobalReconciliationsUpdate: '/setting/company-global-reconciliations-update',
    getMarkettingReconciliation: '/setting/get-marketing-reconciliation',
    updateMarkettingReconciliation: '/setting/marketing-reconciliation-update',
    getTierDuration: '/setting/get-tier-duration',
    updateReconciliation: '/setting/updateReconciliationSchedule',
    getSettingPayroll: '/setting/get-company-payrolls',
    getmarginofdiffrence: '/setting/get-margin-difference',
    updatemarginofdiffrence: '/setting/margin-difference-update',
    getLocationsList: '/setting/locations',
    exportLocationData: '/setting/export_location',
    deleteLocation: '/setting/locations',
    getCostCenterList: '/setting/cost-center-list',
    getCostCenterListbyID: '/setting/cost-center',
    getParentChildCostCenter: '/setting/parent-child-cost-center',
    getDepartmentList: '/setting/department',
    getPositionByDepartment: '/setting/get_data_position_from_department',
    getIncompleteAccountAlert: '/setting/get-incomplete-account-alert',
    getCompleteAccountAlert: '/setting/get-marketing-deal-alert',
    getPositionList: '/setting/position-commission',
    deletePositionPlan: '/setting/position-commission',
    addlocation: '/setting/locations',
    updatelocation: '/setting/update-locations',
    getStateList: '/setting/state',
    getRecuirter: '/hiring/recruiter_filter',
    getcostcenter: '/setting/cost-center-dropdown',
    getParentCostCenterList: '/setting/parent-cost-center',
    getAllStatesWithOffices: '/setting/get_all_state_with_office',
    getAllOfficeLocation: '/setting/AllUseLocation',
    upComingLocationRedlines: '/setting/getFutureRedLineByLocation',
    addcostcenter: '/setting/cost-center',
    updatecostcenter: '/setting/cost-center',
    getdartmentdropdown: '/setting/drop-down-department',
    adddepartment: '/setting/department',
    addposition: '/setting/add-position',
    updatePositions: '/setting/update-position',
    updatePosition: 'setting/position-commission',
    getposition: '/setting/position-dropdown',
    getPositionById: '/setting/position-commission',
    checkReconciliationSetting: '/setting/checkReconciliationSetting',
    createtier: '/setting/create-tier-configure',
    getPositionSetting: '/setting/positions_status',
    setupPosition: '/setting/position-commission',
    getdepartmentlist: '/setting/department-dropdown',
    deletelocation: '/setting/locations',
    disablecostcenter: '/setting/cost-center-disable',
    updatedepartment: '/setting/update-department',
    deletedepartment: '/setting/delete-department',
    getPositionListByDepartmentId: '/setting/positionByDepartmentID',
    reAssignManager: '/management/update-user-manager',
    getAllManagerlist: '/setting/managerList',
    updatetierlevel: '/setting/tier-duration-level-update',
    getteamlist: '/setting/teams',
    updatecommission: '/setting/position-commission',
    deletetier: '/setting/delete-tier-configure',

    // Admin > Position
    userbyPositionID: '/setting/usersBypositionID',

    //Standard > onBoarding Employee
    addonbrdingemployee: '/hiring/onboarding_employee',
    getOnBoardingEmployeeList: '/hiring/onboarding_employee',
    exportOnBoardingEmployeeList: '/hiring/export_onboarding',
    deleteOnBoardingEmployeeList: '/hiring/delete_onboarding_employee',
    getonbordingemployeebyid: '/hiring/onboarding_employee',
    sendemailbyid: '/hiring/send_email_to_onboarding_employee',
    updateonbordingemployee: '/hiring/onboarding_employee',
    addhiringleads: '/hiring/leads_list',
    addLeadWithoutAuth: '/add_lead_without_auth',
    checkDuplicateLead: '/hiring/check_status_email_and_mobile',
    checkDuplicateLeadWithoutAuth: '/check_status_email_and_mobile_without_auth',
    getRecentlyHiredList: '/hiring/recent_hired',
    getHiringProgressList: 'hiring/hiring_progress',
    getHiringProgressChart: '/hiring/hiring_graph',
    getHireLeadsList: '/hiring/leads_list',
    deleteLead: '/hiring/leads_list',
    postRescheduleInterview: '/hiring/interview_reschedule',
    getOrgChartById: '/setting/positionOrgChartByID',
    scheduleInterview: '/hiring/schedule_interview',
    getInterviewTimeSlot: '/hiring/schedule_time',
    changeLeadStatus: '/hiring/changeStatus',
    exportLeadsData: '/hiring/export_leads',
    hiringAssign: '/hiring/assign',
    getLeadComments: '/hiring/get_leads_comments',
    addLeadComments: '/hiring/add_leads_comments',
    replyLeadComments: '/hiring/add_lead_comment_reaply',
    getLeadById: '/hiring/get_leadby_id',
    hireEmployeeDirectly: '/hiring/directHiredEmployee',
    getHiringCalendarEvents: '/CalenderEvent/hiring_event_list',
    getOnBoardingConfiguration: '/hiring/get_onboarding_configuration_employee',
    addOnBoardingConfiguration: '/hiring/onboarding_configuration_employee',
    addOrUpdateOnboardingDynamicAttributes: '/hiring/onboarding_configuration_employee_add',
    deleteOnboardingDynamicAttributes: '/hiring/onboarding_configuration_employee_delete',
    updateHireDateOfEmployee: '/hiring/hired_date_update',

    sendUserCredential: '/hiring/hiredEmployee',

    //Admin > Integrations
    getIntegtationList: '/setting/crm_setting_list',
    getIntegtationById: '/setting/get_crm_setting_by_id/',
    addIntegtationSetting: '/setting/crm_setting',
    updateIntegtationSetting: '/setting/crm_setting_update',
    connectDisconnectIntegtationSetting: '/setting/crm_setting_disconnect',
    getIntegrationLogs: '/reports/api_log_report',
    syncHubSpot: '/hubspotSyncData',

    //Standard > Onboarding Employees > Hire New
    hireNowStep1: '/hiring/onboarding_employee_details',
    hireNowStep2: '/hiring/onboarding_employee_originization',
    hireNowStep3: '/hiring/onboarding_employee_compensation',
    hireNowStep4: '/hiring/onboarding_employee_override',
    hireNowStep5: '/hiring/onboarding_employee_agreement',

    //Admin > Settings > Setup > Schedule Payroll
    getPayFrequencyType: '/setting/frequency-type-dropdown-list',
    updateCompanyPayroll: '/setting/Company-payroll-update',
    getAllWeeklyPayPeriod: '/setting/weeklyPayFrequencyDropdownAll',
    getWeeklyPayPeriod: '/setting/weeklyPayFrequencyDropdown',
    getWeeklyExecutedPayPeriod: '/setting/weeklyPayFrequencyExecutedDropdown',

    getAllMonthlyPayPeriod: '/setting/monthlyPayFrequencyDropdownAll',
    getMonthlyPayPeriod: '/setting/monthlyPayFrequencyDropdown',
    getMonthlyExecutedPayPeriod: '/setting/monthlyPayFrequencyExecutedDropdown',

    // Admin > Settings > Alerts
    putToggleAlerts: '/setting/alert-enable-disable',
    postMarketingDeal: '/setting/alert-marketing-deal',
    createIncompleteAccountAlert: '/setting/alert-incomplete-account',
    getEmailNotificationSetting: 'setting/get_email_notification_setting',
    updateEmailNotificationSetting: 'setting/email_notification_setting',
    updateDomainSetting: '/setting/update_domain_setting',
    deleteDomainSetting: '/setting/delete_domain_setting',
    getDomainSetting: '/setting/get_domain_setting',
    addDomainSetting: '/setting/add_domain_setting',

    //Standard > Management
    getEmployeeListByLocation: '/management/managementEmployeeListByStateIds',
    getEmployeeList: '/management/managementEmployeeList',
    filterEmployeeList: '/management/management-employee-filter',
    addEmployeeDocumentById: '/management/AddDocumentBYUserId',
    updateEmployeeDocumentById: '/management/updateDocumentBYUserId',
    getEmployeeDocumentById: '/management/getDocumentBYUserId',
    getEmployeeSequiDocDocumentById: '/hiring/sequdocs_document_list_by_user_id',
    getOnBoardingEmployeeSequiDocDocumentById:
        '/hiring/sequdocs_document_list_by_onboarding_employees_user_id',
    deleteEmployeeDocumentById: '/management/deleteDocumentBYUserId',
    getDocumentTypeDropdown: '/management/document-type-dropdown',
    getEmployeeChart: '/management/employee_network',
    updateEmployeeUserGroup: '/permission/update_user_group',
    updateUserImage: 'management/updateUserImage',
    userNetworkOveride: '/management/my_overrides',
    overrideOnUser: '/management/mysale_overrides',
    addManualOverride: '/management/manual_overrides',
    addManualOverrideFrom: '/management/manual_overrides_from',
    getManualOverrideData: '/management/get_mysale_overrides',
    editManualOverrideFrom: '/management/edit_manual_overrides_from',
    editManualOverrideOn: '/management/edit_manual_overrides',
    changeOverrideStatus: '/management/my_overrides_enable_disable',
    exportEmployeeData: '/management/exportStandardEmployeeExport',

    // Employee
    getEmployeeProfile: '/hiring/user-profile',
    getEmployeePersonalInfo: '/hiring/user-personal-info',
    getEmployeePackage: '/hiring/user-packege',
    getEmployeeBankingInfo: '/hiring/user-banking',
    getEmployeeTaxInfo: '/hiring/user-tax-info',
    updateEmployeeProfile: '/hiring/update-user-profile',
    updateEmployeePosition: '/hiring/update-user-position',
    updateEmployeeCommission: '/hiring/update-commission',
    getUserRedline: '/hiring/userRedlineHistory',
    updateUserAccountStatus: '/hiring/update-user-account-status',
    getUsersByManagerId: '/management/get-all-users-by-manger',
    transferEmployee: '/hiring/employee_transfer',

    //Admin > Sequifi Docs
    getSequiDocsTemplateCategories: '/hiring/category-dropdown-template',
    getSequiDocsTemplates: '/hiring/template',
    getSequiDocsTopTemplates: '/hiring/sequdocs_category_list_template_count',
    getTemplateHistory: '/hiring/docHistory',
    getSequifiDocTemplateHistory: '/hiring/sequiDoc_template_history',
    getSequiDocsTemplatesByCategory: '/hiring/category-dropdown-template',
    getSequiDocsAgreementList: '/hiring/get_agreements_list',
    getSequiDocsTemplateById: '/hiring/template',
    addSequiDocsTemplate: '/hiring/template',
    updateSequiDocsTemplate: '/hiring/template',
    deleteSequiDocsTemplate: '/hiring/template',
    searchSequiDocsTemplate: '/hiring/search-template',
    sendTemplate: '/hiring/generate-template',
    downloadTemplate: '/hiring/generate-template',
    assignTemplate: '/hiring/add-template-assign',
    getDocumentsList: '/management/DocumentList',
    getNewDocumentsList: '/hiring/sequdocs_document_list',
    addTemplateCategory: '/hiring/add_category_template',
    updateTemplateCategory: '/hiring/editCategoryTemplate',
    deleteSequiDocsCategory: '/hiring/deleteCategoryTemplate',
    deleteSequiDocsParticularTemplate: '/hiring/delete_template',
    addTemplateSettingStep1: '/hiring/add_sequdocs_template',
    updateTemplateSetting: '/hiring/update_template',
    addTemplateAgreementStep4: '/hiring/edit_sequdocs_template_agreements',
    addTemplateSignatureStep2: 'hiring/edit_sequdocs_template_signature',
    addTemplateEditTemplateStep3: '/hiring/edit_sequdocs_template',
    getTemplateListByCategory: '/hiring/sequdocs_template_list',
    getEmailTemplatesList: '/hiring/SequiDocsEmailTemplatesList',
    updateEmailTemplate: '/hiring/updateSequiDocsEmailTemplate',
    getTemplateDetail: '/hiring/sequdocs_template_detail',
    useOrSendSequiDocTemplate: '/hiring/sequdocs_template_usenow',
    useSequiDocsTemplate: '/hiring/sequdocs_send_document/Use',
    testParticularTemplate: '/hiring/sequdocs_send_document/Test',
    downloadParticularTemplate: '/hiring/sequdocs_send_document/Download',
    sendSequiDocTestTemplateEmail: '/hiring/sequdocs_test_template',
    getSmSequiDocData: '/hiring/sequdocs_standerd_template_list',
    searchEmployeeToSendDoc: '/hiring/employee_search_for_send_document',

    //manager > Report
    getManagerReport: 'managerreports/manager_report_office',
    getMySalesReport: '/reports/sales_report',
    getMySalesChart: '/sales/my_sales_graph',
    getReconcilliationReport: '/managerreports/reconciliation',
    getSaleTracking: 'sales/customerSaleTracking',
    getSalesReport: '/managerreports/report_sales_list',
    getSalesGraph: '/managerreports/report_sales_graph',
    getSalesAccountAndInstallRatioGraph: '/managerreports/report_account_install_ratio_graph',

    //Admin Report
    getReconciliationReport: '/reports/reconciliation_report',
    getAdminAllGraphs: '/reports/sales_graph',
    exportAdminSales: '/reports/sales_export',
    getAdminCustomerList: '/reports/sales_report',
    getAdminCostGraph: '/reports/costs_graph',
    getAdminCostReport: '/reports/costs_report',
    getAdminClawBackReport: '/reports/claw_back',
    getAdminPayrollReport: '/reports/payroll_report',
    getAdminPayrollReportByYearMonthAndFrequency: '/reports/get_report_year_month_frequency_wise',
    getAdminPayrollByFilters: '/reports/get_report_year_month_frequency_wise',
    getAdminPendingInstallReport: '/reports/pending_install',
    exportAdminPendingInstallReport: '/reports/export_pending_install',
    getAdminCompanyReport: '/reports/company_report',
    getAdminCompanyGraph: '/reports/company_graph',
    exportPayrollReport: '/payroll/export_payroll_report',
    exportCostData: '/reports/costs_export',
    exportReconciliationReport: '/reports/reconciliation_export',
    exportAdminClawBackReport: 'excel/clawbackSalesExport',

    // Requests & Approval
    getAdjustmentTypeList: '/RequestApproval/adjustment-type',
    getAlLRequestsList: '/RequestApproval/request-approval',
    searchRequest: '/RequestApproval/request-approval',
    getRequestDetailsByRequestNumber: '/RequestApproval/getRequestApprovalStatusByReq_No',
    updateStatusOfRequest: '/RequestApproval/update-status-of-request',
    addRequest: '/RequestApproval/request-approval',
    addRequestApprovalComment: '/RequestApproval/requestApprovalComment',
    getAllApprovalList: '/RequestApproval/approval-list',
    searchApproval: '/RequestApproval/search-approval',
    approvalHistory: '/RequestApproval/approvalListForHistory',

    //Admin Permmission
    getGroupList: '/permission/group_list',
    getPoliciesList: '/permission/policies_list',
    deletePermission: '/permission/delete_permission',
    getPermission: '/permission/get_permission',
    addGroupPermission: '/permission/add_group_permission',
    updateGroupPermission: '/permission/update_group_permission',
    groupPolicyList: '/permission/group_policies_list',
    getListofGroup: '/permission/group_by_user_list',

    //SM > My Sales
    getMySalesGraph: '/sales/my_sales_graph',
    getMySalesList: '/sales/sales_list',
    getMySalesAccountInitialRatioGraph: 'sales/account_install_ratio_graph_api',
    getMySalesOverrideData: '/sales/getOverrides',
    getMyRecalculateData: '/sales/recalculate_sale_data',

    //Closer and Setter
    getSalesCloserList: '/setting/get-closer',
    getSalesSetterList: '/setting/get_setter_dropdown',
    getSalesByPid: '/reports/sales_by_pid',
    updateSetterByPid: '/setting/update-setter-by-pid',
    updateCloserByPid: '/setting/update_pid_with_closer',

    // Admin > Alert Center
    // getAlertCenterList: '/setting/alert-center',
    getAlertCenterList: '/setting/alert_center_details',
    getMissingDataAlertCenter: '/setting/sales-detail-by-pid',
    updateMissingDataAlertCenter: '/setting/update-alert-center-data',
    updateMissingPayPeriod: '/setting/updatePayRollMissingPeriod',
    getAdderByPidAlertCenter: '/setting/adders_by_pid',
    getClawbackByPidAlertCenter: '/setting/adjust_clawback_sale_data',
    getPayrollByidAlertCenter: '/payroll/addAlertToPayroll',
    getPayRollMissingDetails: '/setting/payRollMissingDetailByPid',
    getAllAlertMissingData: '/setting/payRollMissingDetailByPid',
    getSalesAndMissingRepMissingDetail: '/setting/getMissingDetailByPid',
    searchAllAlertData: '/reports/global_search',

    //Admin > Settings > POsition update
    updatePositionHierarchy: '/setting/update_position_hierarchy',
    updatePositionGroup: '/setting/update-position-group',
    positionOrgChart: '/setting/positionOrgChart',

    //Standard > Calander > Calander Event
    addCalanderEvent: '/CalenderEvent/add-event',
    getCalanderEventList: '/CalenderEvent/event-list',
    deleteCalanderEvent: 'CalenderEvent/delete',
    updateCalanderEvent: '/CalenderEvent/edit_event',
    getGlobalSheduleTimeCalendar: '/hiring/schedule_time_slot',
    setSheduleTimeSlot: '/hiring/user_schedule_time',
    getUserSheduleTime: '/hiring/get_user_schedule_time',

    //Standard > Reports > Sales > Account Overrides
    getAccountOverridesbyPid: '/sales/account_overrides',

    //Sm > management > Teams
    getManagmentTeams: '/management/management-team',
    getTeamLeadByOfficeId: '/setting/getUserByOfficeIDForTeamLead',
    getTeamMembersByOfficeId: '/setting/getUserByOfficeIDForTeamMember',
    deleteManagmentTeamMember: '/management/delete-management-team-member',
    deleteTeam: '/management/delete_team',
    addManagementTeam: '/management/management-team',
    updateManagementTeam: '/management/update-management-team',

    // Admin > Reports > Sales > Add Sales
    addSale: '/setting/add_manual_sale_data',
    salesAccountSummaryData: '/reports/salesAccountSummary',
    salesAccountSummarybyPosition: '/reports/salesAccountSummaryByPosition',
    getCompanyAccountSummary: '/reports/company_margin_summary',

    //   Get Super Admin Access
    getSaleDataForSuperAdmin: '/setting/get_sales_data_by_super_admin',

    // Payroll
    getPayrollData: '/payroll/payroll_data',
    getPayrollHistory: '/payroll/get_summary_payroll',
    getReportPayrollHistory: '/reports/get_report_summary_payroll',
    getCommissionDetails: '/payroll/commission_details',
    getReportCommissionDetails: '/reports/commission_details',
    getPaystubCommissionDetails: '/managerreports/commission_details',
    getReimbursementDetails: '/payroll/reimbursement_details',
    getReportReimbursementDetails: '/reports/reimbursement_details',
    getPaystubReimbursementDetails: '/managerreports/reimbursement_details',
    getOverrideDetails: '/payroll/override_details',
    getReportOverrideDetails: '/reports/override_details',
    getPaystubOverrideDetails: '/managerreports/override_details',
    editOverrideDetails: '/payroll/payroll_overrides_edit',
    editCommissionDetails: '/payroll/payroll_commission_edit',
    editDeductionDetails: '/payroll/updatepayrollDeductionsByEmployeeId',
    getAdjustmentDetails: '/payroll/adjustment_details',
    getReportAdjustmentDetails: '/reports/adjustment_details',
    getPaystubAdjustmentDetails: '/managerreports/adjustment_details',
    deleteAdjustmentDetails: '/payroll/delete_adjustement',
    getPaymentRequestDetails: '/payroll/payment_request',
    payNowPaymentRequest: '/payroll/paymentRequestPayNow',
    getAdvancePaymentRequestDetails: '/payroll/advance_payment_request',
    updatePaymentRequest: '/payroll/update_payment_request',
    getReconciliationDetail: '/payroll/reconciliation_details',
    getPayrollDeductionDetail: '/payroll/payrollDeductionsByEmployeeId',
    getPaystubDeductionDetail: '/managerreports/override_details',
    updateReconciliationDetail: '/payroll/reconciliations_adjustment',
    payrollReconciliationHistory: '/payroll/payrollReconciliationHistory',
    oneTimePayment: '/payroll/create_onetime_payment',
    oneTimePaymentHistory: '/payroll/get_onetime_payment_history',
    onTimePaymentTotal: '/payroll/onetime_payment_total',
    downloadCsvFile: '/payroll/export_payment_history',
    finilizeReconciliation: '/payroll/finalize_reconciliation',
    addToPayrollReconciliation: '/payroll/add_reconciliation_to_payroll',
    getFinilizePayroll: '/payroll/get_finalize_payroll',
    finilizePayroll: '/payroll/finalize_Payroll',
    executePayroll: '/payroll/execute_Payroll',
    updatePayrollDetail: '/payroll/update_payroll',
    adjustPayrollDetail: '/payroll/payroll_adjustment',
    moveToNextPayroll: '/payroll/payroll_move_next_payroll',
    markAsPaidPayroll: '/payroll/payroll_mark_as_paid',
    moveToReconciliationPayroll: '/payroll/moveToReconciliations',
    payrollReconClawbackPopUp: '/payroll/payrollReconClawbackbyEmployeeId',
    payrollReconOverridePopUp: '/payroll/payrollReconOverridebyEmployeeId',
    payrollReconCommissionPopUp: '/payroll/payrollReconCommissionbyEmployeeId',
    closePayroll: '/payroll/close_payroll',
    undoReconPayroll: '/payroll/payroll_reconciliation_rollback',
    undoPaidPayroll: '/payroll/payroll_mark_as_unpaid',
    undoMoveToNextPayroll: '/payroll/payroll_undo_next_payroll',

    //Onboarding Employees>After login
    getOnBoardingEmployeeDetail: '/hiring/get_onboarding_employee',
    updateOnBoardingEmployeeDetail: '/hiring/update_onboarding_employee',
    changeOnboardingEmployeeStatus: '/hiring/onBoardingChangeStatus',
    changeOnboardingEmployeeAgreementStatus: '/hiring/accept_decline_agreement',
    getOnboardingConfiguration: '/hiring/get_onboarding_configuration_employee',
    uploadOnBoardingDocument: '/management/AddDocumentBYUserId',
    deleteOnBoardingDocument: '/management/deleteDocumentBYUserId',

    //admin setup payFrequency
    getPayFrequencySetting: '/setting/listPayfrequencySetting',
    addPayFrequencySetting: '/setting/AddPayfrequencySetting',

    //New Employee Package
    getuserEmploymentPackageByid: '/hiring/user-detail-by-id',
    updateUserPersonalData: '/hiring/user_details',
    updateUserOrganizationData: '/hiring/user_organization',
    updateUserDeductionData: '/hiring/update_user_deduction',
    updateUserOverrideData: '/hiring/user_override',
    updateUserAgreementData: '/hiring/user_agreement',
    updateUserCompensation: '/hiring/user_compensation',

    //Search API
    userByOfficeId: '/setting/getUserByOfficeID',

    //Admin Dashboard API
    getDashboardPayrollSummary: '/dashboard/admin/get_payroll_summary',
    getTopPayrollLocations: '/dashboard/adminTopPayRollLocation',
    getAnnouncementList: '/dashboard/get_list_announcement',
    getAnnouncementCardData: '/dashboard/get_standard_announcement_card',
    getAlertList: '/dashboard/dashboard_alert_center',
    getHiringAlertList: '/hiring/alertScheduleInterview',
    getDashboardOfficeSalesPerformance: '/dashboard/adminOfficePerformance',
    getOfficeSalesPerformanceGraph: '/dashboard/officePerformanceSelesKw',
    getSmDashboardSalesReport: '/dashboard/salesReport',
    getSmOfficeSalesPerformance: '/dashboard/officePerformance',
    getSmOfficePeformanceTeam: '/dashboard/officePerformanceSelesTeam',
    getGoalTrackerData: '/dashboard/goalsTracker',
    setGoalTracker: '/dashboard/setGoals',
    getSmOfficeEventList: '/dashboard/event_list',
    addAnnouncement: 'dashboard/add_list_announcements',
    disableAnnouncement: '/dashboard/announcement_disable',
    deleteAnnouncement: 'dashboard/delete_list_announcements',

    //Past pay stub
    getPastPaystubGraphData: '/managerreports/past_pay_stub_graph',
    getPastPaystubTableData: '/managerreports/past_pay_stub',
    getPastPaystubDetail: '/managerreports/past_pay_stub_detail',
    getPastPaystubDetailList: '/managerreports/past_pay_stub_detail_list',
    getCurrentPaystubCustomerDetail: '/managerreports/current_pay_stub_customer_info',
    getCurrentPaystubDetail: '/managerreports/current_pay_stub_detail_list',
    getPastPaystubUserDetail: '/managerreports/past_pay_stub_customer_info',

    //Filters
    locationFilter: '/setting/location_filter',
    positionFilter: '/setting/position-commission',
    leadsFilter: '/hiring/leads_list',
    runPayrollFilter: '/payroll/payroll_data',
    salesReportFilter: '/managerreports/report_sales_list',

    //Standard Request and Approval
    getPidByUser: '/sales/getPidByUser',
    exportApprovalHistory: '/RequestApproval/exportRequestApprovalHistory',

    //Employment Package History
    getEmploymentPackageHistory: '/hiring/get_employment_package_history',
    deleteEmploymentPackageHistory: '/hiring/delete_employment_package_history',
    deleteManualOverrideHistory: '/management/delete_manual_overrides',

    // Setting UserManagement

    getUserManagementList: 'management/userManagementList',
    addNewAdmin: '/hiring/add_admin',
    makeSuperAdmin: '/management/make_user_group_admin',
    suspendAccessOfUser: '/management/suspend_user_access',
    exportUserManagementList: '/management/export_user',

    // Setting Billing Details
    getBusinessAddressList: '/setting/get-business-address',
    updateBusinessAddress: '/setting/update-business-address',
    getSubscriptionList: '/get_subscriptions',
    manageSubscription: '/manage_subscription',
    getBillingHistoryData: '/get_billing',
    getSubscriptionPidData: '/get_pidsdata',
    getBillingPidData: '/get_Sales_Invoice_pids',
    getBillingM2Data: '/get_Sales_Invoice_m2_data',
    getSubscriptionM2CompleteData: '/get_m2data',
    getBillingInvoice: '/get_invoice_data',

    getBillingPaymentGatewayInfo: '/add_payment',
    paymentCallback: '/stripe_callback_url',

    importAdminSalesData: '/reports/sales_import',

    emailSetting: '/email_configuration',
    testEmailSetting: '/email_configuration_check',
    getEmailSetting: '/email_configuration_list',

    getUserAdditionalEmails: '/hiring/users_additional_emails_list',
    deleteUserAdditionalEmail: '/hiring/delete_users_additional_email',
    addUpdateUserAdditionalEmail: '/hiring/add_users_additional_emails',

    //Multi tenency
    companyOnboardSetting: '/company-onboarding',
}

export default EndPoints
